### ISSUE TITLE
Evaluate exposing polygon inundation as WPS

### ISSUE THREAD

**Issue by mmcfarland** [azavea/usace-flood-geoprocessing#32]
Evaluate the amount of effort required to turn our simple REST endpoint for inundation requests on polygon input as an OGC standards compliant  Web Processing Service API.

http://www.opengeospatial.org/standards/wps

**Comment by jtarricone** [comment]
The Cliff's Notes-->

Compliance with the OGC standard is determined by whether an endpoint passes a battery of tests, as enumerated in [this pulse-pounding tour-de-force](http://docs.opengeospatial.org/is/14-065/14-065.html) with corollaries and clarification in [this legal thrill-ride](http://portal.opengeospatial.org/files/?artifact_id=38867). The absolutely necessary endpoints are `GetCapabilities,` `DescribeProcess`, and `Execute`, and if the service is to meet the standards for an asynchronous process, it must also implement `GetStatus`, `DismissRequest` and `GetResult`.

In each case, the requests are expected to be consistent with a series of XML schema (which means that the API presumably has to ensure conformance and throw if it's out of compliance). It goes without saying, the responses are similarly required to conform to a series of schemas. The plot thickens, though, because there's some amount of server-side work that seems to be implied by what the responses are expected to look like. For instance: asynchronous jobs are expected to have unique identifiers and be retrievable as such; job status calls should note the percent-completion, the next polling time, and the cutoff time for getting the results; the description of the API is expected to be usable on its own to use the rest of the service (that's actually how the test suite goes about testing an API).

Luckily, there appears to be an [existing test suite](http://opengeospatial.github.io/teamengine/index.html) that can validate an API's conformance to the standard. I set it up locally and tested it against some reference implementations listed [here](https://github.com/opengeospatial/cite/wiki/Reference-Implementations), and it appeared to be in working order. However, there aren't any reference implementations of the WPS standard, so I don't know for certain that the test script actually tests properly, but it's probably a safe bet.

The two main steps to get the Flask API in compliance are 1) exposing the endpoints and actually wiring everything correctly, and 2) adding XML de-/serialization to the compliant interface implementations (I think that the API could remain as it is, with JSON serialized data, and the OGC compliant endpoints implemented alongside them). There are only a handful of methods that have to be implemented, but the requirements for them are pretty strict and detailed.

The process to implement this would probably best start with setting up the test suite, and then iteratively adding to or modifying the API. The standard is sufficiently complex and obtuse that it would be more expedient to just inch closer than to try to get it right the first time. Adding the XML de-/serialization is probably not necessary in any serious fashion to actually meet the standards, so it could be handled separately or punted until later. I don't think the task would be especially difficult per se, but there's definitely a possibility that it sinks into a well of tedium on any combination of the finer points of the standard.

**Comment by mmcfarland** [comment]
+1, good assessment.
